### ISSUE TITLE
PropPack/objects/doorprops/roundeddoorprop/roundeddoorprop.frames causing error on linux server

### ISSUE THREAD

**Issue by S1M1S** [asperrusual/PropPack#2]
[Error] Exception caught loading asset: /objects/doorprops/roundeddoorprop/roundeddoorprop.png:default, (ImageException) call to subImage with pos (0, 0) size (32, 40) out of image bounds (16, 40)

Editing roundeddoorprop.frames to:
    
{
  "frameGrid": {
    "size": [ 16, 40 ],
    "dimensions": [ 1, 1 ],
    "names": [
      [ "default" ]
    ]
  }
}

fixed the issue

**Comment by asperrusual** [comment]
this should be fixed with the latest patch. sorry for the inconvenience!

**Comment by S1M1S** [comment]
Legend!
